# -*- coding: utf-8 -*-
"""INP-Former.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Puudg6fZ9p-JqwsKGNBTDjd0UjB0CA67

#INP-Former

Bu notebook'ta, ahşap yüzeylerdeki anomalileri tespit etmek için bir *INP-Former* modeli geliştirilecek ve eğitilecektir.

##1. Ortam Kurulumu

###1.1 Google Drive Bağlantısı
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive

"""###1.2 INP-Former Deposunun Klonlanması"""

!git clone https://github.com/gmzdag/wood-anomaly-detection.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/wood-anomaly-detection/models/INP-Former/src

"""###1.3 Gerekli Kütüphanelerin Kurulumu"""

!pip install -r requirements.txt

!pip install kornia

!pip install numpy==1.26.4

!pip install adeval

"""## 2. Model Eğitimi

####2.1 20 Epoch İle Model Eğitimi

**Parametre Açıklamaları:**

- `!python INP_Former_Multi_Class.py`: Çalıştırılacak Python betiği. INP-Former modelinin çok sınıflı versiyonu için eğitim veya test işlemlerini yürütür.
- `--dataset` : Kullanılacak veri setini belirtir.
- `--data_path `: Veri setinin bulunduğu dizin yolu. Betik bu yoldaki veri setini işleyecektir.
- `--save_dir` : Model ağırlıklarının, logların kaydedileceği dizin.
- `--total_epochs `: Modelin kaç epoch  boyunca eğitileceğini belirtir. Burada 20 epoch olarak ayarlanmıştır.
- `--phase `: Betiğin hangi modda çalışacağını belirtir. "train" değeri, modelin eğitim modunda çalışacağını gösterir.
"""

!python INP_Former_Multi_Class.py\
  --dataset MVTec-AD\
  --data_path /content/drive/MyDrive/processed_dataset \
  --save_dir ./saved_results/ \
  --total_epochs 20 \
  --phase train

"""Modeli test etmek için `phase` `test` moduna ayarlandı."""

!python INP_Former_Multi_Class.py\
  --dataset MVTec-AD\
  --data_path /content/drive/MyDrive/processed_dataset \
  --save_dir ./saved_results/ \
  --total_epochs 1 \
  --phase test

"""####2.2 30 Epoch İle Model Eğitimi"""

!python INP_Former_Multi_Class.py\
  --dataset MVTec-AD\
  --data_path /content/drive/MyDrive/processed_dataset \
  --save_dir ./saved_results/ \
  --total_epochs 30 \
  --phase train

!python INP_Former_Multi_Class.py\
  --dataset MVTec-AD\
  --data_path /content/drive/MyDrive/processed_dataset \
  --save_dir ./saved_results/ \
  --total_epochs 1 \
  --phase test